Added BetterPassword version 1.2
pkp/plugin-gallery pull request #128
Opened 2021-11-29 20:53 UTC by wopsononock

2021-11-29 21:17 UTC, ctgraham commented
Thanks, @wopsononock !

2021-11-30 13:03 UTC, asmecher commented
@ctgraham, have you reviewed this?

2021-11-30 13:33 UTC, ctgraham commented
> @ctgraham, have you reviewed this?

@asmecher , meet @wopsononock . @wopsononock will be updating each of our plugins to support 3.3. Our process has an internal review within ulsdevteam prior to packaging and releasing the plugin version, then the PR to plugin-gallery.

2021-11-30 14:06 UTC, asmecher commented
Ah, great! I figured it was something like that. Good to meet you, @wopsononock! Just to confirm, @ctgraham, has the internal review been completed or does that kick off with this PR?

2021-11-30 14:25 UTC, ctgraham commented
Our internal review for this is completed; each review will precede the packaging/release, which will precede the PR here.

2021-11-30 14:44 UTC, asmecher commented
Gotcha, so this is ready for merging?

2022-02-09 15:54 UTC, ctgraham commented
Found a [bug with the version.xml](https://github.com/ulsdevteam/pkp-betterPassword/issues/29) here, with an upcoming patch.

2022-02-15 21:07 UTC, ctgraham commented
@wopsononock , please update this PR with the new md5 hash for the release.

2022-03-15 19:16 UTC, ctgraham commented
@wopsononock , this md5 is still not matching.

2022-03-16 20:29 UTC, wopsononock commented
I'm calculating the md5 using md5sum betterPassword-v1.2.0-0.tar.gz and coming up with the same thing.  I must be missing something here.

2022-03-16 21:30 UTC, ctgraham commented
The download link is a tar.gz, but the [value in the xml is a .tgz](https://github.com/pkp/plugin-gallery/pull/128/files#diff-40e37cab0fab1110313d27d74efc0d9fef18d8bba94682eb6841a45d983147acR4526).  The MD5 which Travis CI is getting must be from a 404.

2022-04-15 13:48 UTC, ctgraham commented
@wopsononock , please add 3.3.0-9 and 3.3.0-10 to this PR.

2022-05-02 13:59 UTC, ctgraham requested changes

2022-05-02 13:59 UTC, ctgraham commented on plugins.xml
> +				<version>3.3.0.8</version>
Still missing 3.3.0-9 and 3.3.0-10.

2022-05-10 18:31 UTC, merged