Added emailIssueToc plugin compatibility for 3.2+ and 3.3
pkp/plugin-gallery pull request #146
Opened 2022-05-03 13:27 UTC by wopsononock

2022-05-03 13:50 UTC, ctgraham approved these changes

2022-05-03 14:10 UTC, ctgraham requested changes

2022-05-03 14:10 UTC, ctgraham commented on plugins.xml
> +			<compatibility application="omp">
Please rescind the compatibility statement with OMP and OPS.  This plugin is specific to Journal Issue Table of Contents.

2022-05-06 16:29 UTC, ctgraham requested changes

2022-05-06 16:29 UTC, ctgraham commented on plugins.xml
> +			<compatibility application="ojs2">
This compatibility statement should be merged with the above, for just one "ojs2" application statement.

2022-05-06 16:29 UTC, ctgraham commented on plugins.xml
> +			<compatibility application="omp">
OMP and OPS compatibility should be removed here as well.

2022-05-10 14:20 UTC, ctgraham approved these changes

2022-05-10 19:40 UTC, merged

2022-05-10 19:40 UTC, asmecher commented
Merged, thanks!